// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/06/2026, 14.45.27
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/TestLaB/Fitur/fe-fitur/components/**/*.{vue,js,jsx,mjs,ts,tsx}","components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/TestLaB/Fitur/fe-fitur/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/TestLaB/Fitur/fe-fitur/plugins/**/*.{js,ts,mjs}","D:/TestLaB/Fitur/fe-fitur/composables/**/*.{js,ts,mjs}","D:/TestLaB/Fitur/fe-fitur/utils/**/*.{js,ts,mjs}","D:/TestLaB/Fitur/fe-fitur/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/TestLaB/Fitur/fe-fitur/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/TestLaB/Fitur/fe-fitur/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/TestLaB/Fitur/fe-fitur/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;