-- Seed data for dbbrowseconfigs
-- Generated from BrowseService::getConfigMap()
-- Run after migration

INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10051', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', '[Simbol,Tipe,DK]', '[LEFT JOIN DBAKSESPERKIRAAN ak ON ak.Perkiraan = DBPERKIRAAN.Perkiraan AND ak.UserMode = :userMode]', 'AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1005', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', '[Simbol]', NULL, 'AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100444', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, NULL, 'AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10053', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, NULL, 'AND DBPERKIRAAN.Kelompok = 3 AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10054', 'DBLRHPP', 'Nomor', 'Keterangan', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10055', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, '[LEFT JOIN DBAKSESPERKIRAAN ak ON ak.Perkiraan = DBPERKIRAAN.Perkiraan AND ak.UserMode = :userMode]', 'AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10059', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, '[LEFT JOIN DBAKSESPERKIRAAN ak ON ak.Perkiraan = DBPERKIRAAN.Perkiraan AND ak.UserMode = :userMode]', 'AND DBPERKIRAAN.Tipe = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100409', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, '[INNER JOIN DBPOSTHUTPIUT pht ON pht.Perkiraan = DBPERKIRAAN.Perkiraan]', 'AND pht.Kode = ''HT''', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100408', 'DBPERKIRAAN', 'Perkiraan', 'Keterangan', NULL, '[INNER JOIN DBPOSTHUTPIUT pht ON pht.Perkiraan = DBPERKIRAAN.Perkiraan]', 'AND pht.Kode = ''PT''', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10141', 'vwBrowsSupp', 'KodeCustSupp', 'NamaCustSupp', '[Alamat,Telpon]', NULL, 'WHERE IsAktif = 1 AND Jenis = 2', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10142', 'vwBrowsCust', 'KodeCustSupp', 'NamaCustSupp', '[Alamat,Kota,DueDate,JENIS,IsPpn]', NULL, 'WHERE IsAktif = 1 AND Jenis = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10143', 'vwBrowsExpedisi', 'KodeCustSupp', 'NamaCustSupp', '[Alamat,Telpon]', NULL, 'WHERE IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('911', 'DBBARANG', 'KodeBrg', 'NamaBrg', '[Isi2,Sat1,Sat2]', NULL, 'AND KodeGrp = ''BJ''', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('912', 'DBBARANG', 'KodeBrg', 'NamaBrg', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('913', 'DBBARANG', 'KodeBrg', 'NamaBrg', '[Isi2,NFix,Kontrak]', '[LEFT JOIN DBARANGCUSTOMER bc ON bc.KodeBrg = DBBARANG.KodeBrg]', NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('914', 'DBLOKASI', 'Lokasi', 'Lokasi', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('915', 'DBBARANG', 'KodeBrg', 'NamaBrg', NULL, NULL, 'AND IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('917', 'DBBARANG', 'KodeBrg', 'NamaBrg', NULL, NULL, 'AND IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('120302', 'vwBarang', 'KodeBrg', 'NamaBrg', '[Sat1,Sat2,Isi1,Isi2,NFix]', NULL, 'AND (IsBarang = 1 OR IsBarang = 2) AND IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('3001101', 'DBBARANG', 'KodeBrg', 'NamaBrg', '[Sat1,Sat2,Isi]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('916', 'DBGUDANG', 'KodeGdg', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('11002', 'DBGUDANG', 'KodeGdg', 'Nama', '[Alamat]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('11009', 'DBGUDANG', 'KodeGdg', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1004', 'DBDEVISI', 'Devisi', 'NamaDevisi', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('11011', 'DBKOTA', 'KodeKota', 'NamaKota', '[KodeArea,NamaArea]', '[LEFT JOIN DBAREA ar ON ar.KodeArea = DBKOTA.KodeArea]', NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110011', 'DBSUBGROUP', 'KodeSubGrp', 'NamaSubGrp', NULL, '[LEFT JOIN DBGROUP g ON g.KodeGrp = DBSUBGROUP.KodeGrp]', 'AND g.KodeGrp NOT IN (''BJ'',''BU'')', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1100112', 'DBGROUP', 'KodeGrp', 'Nama', NULL, NULL, 'AND KodeGrp NOT IN (''BJ'',''BU'')', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110012', 'DBGROUP', 'KodeGrp', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110013', 'DBGROUP', 'KodeGrp', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110014', 'DBSUBGROUP', 'KodeSubGrp', 'NamaSubGrp', '[KodeGrp,Nama]', '[LEFT JOIN DBGROUP g ON g.KodeGrp = DBSUBGROUP.KodeGrp]', NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('157', 'DBSUBGROUP', 'KodeSubGrp', 'NamaSubGrp', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1576', 'DBKARYAWAN', 'KeyNIK', 'Nama', '[NIK]', NULL, 'AND IsAktif = 1 AND KodeBag NOT IN (''ASM'')', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1577', 'DBKARYAWAN', 'NIK', 'Nama', NULL, '[LEFT JOIN DBASM asm ON asm.KeyNIK = DBKARYAWAN.KeyNIK]', 'AND DBKARYAWAN.IsAktif = 1 AND asm.KeyNIK IS NULL', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('15779', 'DBKARYAWAN', 'NIK', 'Nama', NULL, NULL, 'AND IsAktif = 1 AND KodeBag NOT IN (''ASM'')', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('15780', 'DBKARYAWAN', 'NIK', 'Nama', '[Tarif]', '[LEFT JOIN DBTARIFTENAKER tt ON tt.KeyNIK = DBKARYAWAN.KeyNIK]', 'AND DBKARYAWAN.IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100413', 'DBAKTIVA', 'NoMuka', 'Keterangan', '[KodeBag,Devisi]', '["LEFT JOIN DBBAGIAN bg ON bg.KodeBag = DBAKTIVA.KodeBag","LEFT JOIN DBPERKIRAAN pk ON pk.Perkiraan = DBAKTIVA.Perkiraan"]', NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100412', 'DBAKTIVA', 'NoMuka', 'Keterangan', NULL, NULL, 'AND Kelompok = 0', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100405', 'DBGIRO', 'NoGiro', 'Bank', '[TglGiro,Jumlah,Valas,Kurs]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('100406', 'DBGIRO', 'NoGiro', 'Bank', '[TglGiro,Jumlah,Valas,Kurs]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1006', 'DBVALAS', 'KodeVls', 'NamaVls', '[Kurs]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('11001', 'DBVALAS', 'KodeVls', 'NamaVls', '[Kurs]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('2082', 'DBVALAS', 'KodeVls', 'NamaVls', '[Kurs]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1008', 'DBKATEGORI', 'KodeKategori', 'Keterangan', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10081', 'DBKATEGORIBRGJADI', 'KodeKategori', 'Keterangan', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1007', 'DBARUSKAS', 'Kodeak', 'Namaak', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10071', 'DBARUSKASDET', 'Kodesubak', 'Namasubak', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1002', 'DBBAGIAN', 'KodeBag', 'Namabag', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('10021', 'DBDEPART', 'KdDep', 'NmDep', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1003', 'DBJABATAN', 'KodeJab', 'Namajab', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('251050', 'DBTIPETRANS', 'KodeTipe', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('30056', 'DBTIPETRANS', 'KodeTipe', 'Nama', '[KodeSubTipe]', '[LEFT JOIN DBSUBTIPETRANS st ON st.KodeTipe = DBTIPETRANS.KodeTipe]', NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('30057', 'DBTIPETRANS', 'KodeTipe', 'Nama', NULL, NULL, 'AND IsJasaBeliJual = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110015', 'DBJNSTAMBAHAN', 'KodeJnsTambahan', 'Nama', NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('110016', 'DBBARANG', 'KodeBrg', 'NamaBrg', NULL, NULL, 'AND KodeGrp NOT IN (''BJ'',''BU'') AND IsAktif = 1', NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1250', 'DBEXPEDISI', 'KodeExp', 'NamaExp', '[Alamat1,Alamat2,Kota]', NULL, NULL, NULL, NULL, 1);
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('91117', 'vwBrowsSPK', 'NOSPK', 'KodeBrg', '[NamaBrg,NOSO,NamaCustSupp]', '["LEFT JOIN DBBARANG b ON b.KodeBrg = vwBrowsSPK.KodeBrg","LEFT JOIN DBSO c ON c.NOBUKTI = vwBrowsSPK.NOSO","LEFT JOIN DBCUSTSUPP d ON d.KodeCustSupp = c.KodeCustSupp"]', NULL, NULL, NULL, 1);

-- Entry with alias_fields and parent_filters (special case: 1014)
-- Note: aliasfields and parentfilters stored as JSON string, escape quotes for SQL
INSERT INTO dbbrowseconfigs (kodebrowse, tablename, keyfield, labelfield, additionalfields, joins, whereextra, aliasfields, parentfilters, isactive) VALUES ('1014', 'vwGroupCustSupp', 'KodeCustSupp', 'cs_NamaCustSupp', '["cs_Alamat","cs_Kota","Perkiraan"]', '["LEFT JOIN DBCUSTSUPP cs ON cs.KodeCustSupp = vwGroupCustSupp.KodeCustSupp"]', NULL, '{"cs_NamaCustSupp":"cs.NamaCustSupp","cs_Alamat":"RTRIM(LTRIM(ISNULL(cs.Alamat1,\'\') + CASE WHEN ISNULL(cs.Alamat2,\'\')=\'\' THEN \'\' ELSE \' \' + cs.Alamat2 END))","cs_Kota":"cs.Kota"}', '[{"source_column":"Perkiraan","operator":"=","type":"exact"}]', 1);
